export const ALL_TOUR_REQUEST = 'ALL_TOUR_REQUEST';
export const ALL_TOUR_SUCCESS = 'ALL_TOUR_SUCCESS';
export const ALL_TOUR_FAIL = 'ALL_TOUR_FAIL';

export const CLEAR_ERROR = 'CLEAR_ERROR';

export const TOURS_BY_TAG_REQUEST = 'TOURS_BY_TAG_REQUEST';
export const TOURS_BY_TAG_SUCCESS = 'TOURS_BY_TAG_SUCCESS';
export const TOURS_BY_TAG_FAIL = 'TOURS_BY_TAG_FAIL';

export const TOUR_DETAIL_REQUEST = 'TOUR_DETAIL_REQUEST';
export const TOUR_DETAIL_SUCCESS = 'TOUR_DETAIL_SUCCESS';
export const TOUR_DETAIL_FAIL = 'TOUR_DETAIL_FAIL';

export const LIKE_TOUR_REQUEST = 'LIKE_TOUR_REQUEST';
export const LIKE_TOUR_SUCCESS = 'LIKE_TOUR_SUCCESS';
export const LIKE_TOUR_FAIL = 'LIKE_TOUR_FAIL';

export const ALL_CURRENT_USER_TOUR_REQUEST = 'ALL_CURRENT_USER_TOUR_REQUEST';
export const ALL_CURRENT_USER_TOUR_SUCCESS = 'ALL_CURRENT_USER_TOUR_SUCCESS';
export const ALL_CURRENT_USER_TOUR_FAIL = 'ALL_CURRENT_USER_TOUR_FAIL';
