export const ALL_TOUR_REQUEST = 'ALL_TOUR_REQUEST';
export const ALL_TOUR_SUCCESS = 'ALL_TOUR_SUCCESS';
export const ALL_TOUR_FAIL = 'ALL_TOUR_FAIL';

export const CLEAR_ERROR = 'CLEAR_ERROR';

export const TOURS_BY_TAG_REQUEST = 'TOURS_BY_TAG_REQUEST';
export const TOURS_BY_TAG_SUCCESS = 'TOURS_BY_TAG_SUCCESS';
export const TOURS_BY_TAG_FAIL = 'TOURS_BY_TAG_FAIL';
